export const TRAPEZOID_TYPES = {TRAPEZOID:1};
export const ROOF_TYPE = {ISKURIT:1,KAL_ZIP:2,FLAT:3};
export const FETOT_DIRECTION = {PARALLEL:1, PERPENDICULAR:2};
export const PANEL_TYPES = {
    VERTICAL_1:1,
    VERTICAL_2:2,
    VERTICAL_3:3,
    HORIZANTAL_1_VERTICAL_1:4,
    VERTICAL_1_HORIZANTAL_1:5,
    VERTICAL_2_HORIZANTAL_1:6,
    VERTICAL_1_HORIZANTAL_1_VERTICAL_1:7,
    HORIZANTAL_1_VERTICAL_2:8,
    HORIZANTAL_1:9
}
export const PANEL_WIDTH = 1030;
export const PANEL_HEIGHT = 2080;
export const DISTANCE_BETWEEN_PANELS = 21;
export const CIRCLE_RADIUS=150;
export const JSKECHER_PREFIX= "TCAD.projects.";